<?php

function emic_cwrc_menu() {
  $items = array();
  $items['cwrc/page'] = array(
    'file' => 'emic_cwrc.inc',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cwrc_page_select_form'),
    'type' => MENU_CALLBACK,
    'access arguments' => array('use CWRC'),
  );

  $items['cwrc/save'] = array(
    'file' => 'emic_cwrc.inc',
    'page callback' => 'save_cwrc_data',
    'type' => MENU_CALLBACK,
    'access arguments' => array('use CWRC'),
  );
  $items['cwrc/getCWRC'] = array(
    'file' => 'emic_cwrc.inc',
    'page callback' => 'get_cwrc_data',
    'type' => MENU_CALLBACK,
    'access arguments' => array('use CWRC'),
  );

  $items['cwrc/setupCWRC'] = array(
    'file' => 'emic_cwrc.inc',
    'page callback' => 'setupCWRC',
    'type' => MENU_CALLBACK,
    'access arguments' => array('use CWRC'),
  );
  return $items;
}

function emic_cwrc_perm() {
  return array(
    'use CWRC',
  );
}


/**
 * Implementation of hook_theme
 */
function emic_cwrc_theme($existing, $type, $theme, $path) {
  $path = drupal_get_path('module', 'emic_cwrc') . '/theme';
  $file = 'emic_cwrc.theme.inc';
   
  return array(
    'emic_cwrc' => array(
      'arguments' => array('src' => NULL), 
      'path' => $path,
      'file' => $file,
      'template' => 'emic-cwrc',
    ), 
  );
}




function emic_cwrc_islandora_book_links($pid) {
  if (!user_access('use CWRC')) {
    return;
  }
  global $base_url;
  $path = drupal_get_path('module', 'emic_cwrc');
  module_load_include('inc', 'islandora_book', 'book_pack_utils');
  $pages = get_page_pids($pid);
  $first_page = $pages[0];
  $cwrc_host = "$base_url/$path/resources/index.php";
  $options = array(
    'attributes' => array('target' => '_blank'),
    'query' => array(
      'PID' => $first_page,
    ),
  );
  $link = l('Edit with CWRCWriter', "$cwrc_host", $options);
  return $link;
}

function emic_cwrc_islandora_book_get_pageview_links($pid) {
  $options = array(
    'attributes' => array('target' => '_blank'),
    'query' => array(
      'PID' => $pid,
    ),
  );

  return l(t('Edit with CWRCWriter'), "sites/all/modules/emic_cwrc/resources/index.php", $options);
}

function emic_cwrc_islandora_tabs($content_models, $pid) {
  global $base_url;
  $content_model_pids = array();
  foreach ($content_models as $content_model) {
    $content_model_pids[] = $content_model->pid;
  }
  if (!in_array('islandora:bookCModel', $content_model_pids)) {
    return;
  }
  module_load_include('inc', 'islandora_book', 'book_pack_utils');
  module_load_include('inc', 'fedora_repository', 'api/fedora_item');
  $page_pids = get_page_pids($pid);
  $src = $base_url . '/sites/all/modules/emic_cwrc/resources/index.php?PID=' . $page_pids[0];
/*   $iframe = '<iframe id="shared_canvas_iframe" src="' . $src . '" scrolling="0" frameborder="0" style="width: 100%; height: 800px;">Errors: unable to load SharedCanavas</iframe>'; */
  $tabset['all_edits_tab'] = array(
    '#type' => 'tabpage',
    '#title' => t("Consolidated editor"),
    '#content' => theme('emic_cwrc', $src),
/*     '#content' => $iframe, */
  );
  return $tabset;
}
